# -*- coding: utf-8 -*-

from odoo import fields, models, _
from odoo.exceptions import UserError


class HrEmployee(models.Model):
    _inherit = 'hr.employee'

    def create_version(self, values):
        self.ensure_one()
        date = values.get('date_version') or fields.Date.context_today(self)
        previous_version = self._get_version(fields.Date.to_date(date)) if self.version_ids else False
        new_version = super().create_version(values)
        if previous_version and new_version and new_version != previous_version:
            previous_version._rail_copy_vacation_lines_to(new_version)
        return new_version

    def action_rail_generate_vacation_line(self):
        today = fields.Date.context_today(self)
        for employee in self:
            version = employee._get_version(today)
            if not version or not version._is_in_contract(today):
                raise UserError(_(
                    'No se encontró una versión laboral vigente para %(employee)s en %(date)s.',
                    employee=employee.name,
                    date=today,
                ))
            # The manual action also repairs balances generated by the previous
            # version of the module using the current contract start date.
            version.rail_generate_vacation_line_for_date(
                today,
                raise_if_exists=False,
                update_existing=True,
            )
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Vacaciones MX'),
                'message': _('Saldo vacacional generado o recalculado correctamente con la antigüedad del primer contrato.'),
                'type': 'success',
                'sticky': False,
            }
        }
